"""add type to products

Revision ID: 02747eef62cd
Revises: c23e3a24c296
Create Date: 2025-09-24 00:46:05.948548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02747eef62cd'
down_revision: Union[str, Sequence[str], None] = 'c23e3a24c296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_products_type'), 'products', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_type'), table_name='products')
    op.drop_column('products', 'type')
    # ### end Alembic commands ###
