"""products, carts, cart_lines, orders

Revision ID: 230d6b1f6acd
Revises: 104bec0554bc
Create Date: 2025-09-24 00:14:45.736676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230d6b1f6acd'
down_revision: Union[str, Sequence[str], None] = '104bec0554bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
