"""add color and size to products

Revision ID: c23e3a24c296
Revises: 230d6b1f6acd
Create Date: 2025-09-24 00:34:00.813693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23e3a24c296'
down_revision: Union[str, Sequence[str], None] = '230d6b1f6acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('color', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('size', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_products_color'), 'products', ['color'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_color'), table_name='products')
    op.drop_column('products', 'size')
    op.drop_column('products', 'color')
    # ### end Alembic commands ###
